services:
  web:
    image: shinsenter/phpfpm-apache:php8 #https://hub.docker.com/r/shinsenter/phpfpm-apache
    restart: on-failure
    command:
      - --config=/etc/grafana-config/grafana.ini
    volumes:
       - ./web/hello/:/var/www/html
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/healthz" ]
      interval: 1s
      start_interval: 0s
      timeout: 10s
      retries: 5
    env_file:
      # Use this optional env file to add any secrets required by data sources you can add to config/grafana/datasources
      - path: ~/.grafana_dev_datasources
        required: false
