{
 "title": "Docker overview with Cadvisor + docker state exporter + node exporter-appletimedk",
 "description": "Docker dashboard via Cadvisor + docker state exporter + node exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Docker ( Cadvisor )", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "expr": "container_state_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Not running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "expr": "container_state_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Prometheus Exporter Status",
   "type": "table",
   "gridPos": { "h": 13, "w": 3, "x": 21, "y": 1 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "container_state_status{name=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[1m])) by (name) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"}) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Created",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 14, "x": 10, "y": 32 },
   "targets": [
    {
     "expr": "count by(name) (count_over_time(container_last_seen{name=~\".+\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[15m])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\",container_label_org_label_schema_group=\"\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Cached Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_cache{image!=\"\",container_label_org_label_schema_group=\"\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image!=\"\",container_label_org_label_schema_group=\"\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\",container_label_org_label_schema_group=\"\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Unsued", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum(container_start_time_seconds) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(container_start_time_seconds) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{container_label_com_docker_compose_project=~\".*\"}) / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{instance=~\"192.168.0.196:4040\",name=~\".+\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{instance=~\"192.168.0.196:4040\",name=~\".+\"})/86400",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_state_status{instance=~\"192.168.0.196:8085\",name=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 120 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(container_last_seen) by (name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "https://grafana.daddylars.dk/d/htoVWdxGt/docker-cadvisor?orgId=1&refresh=5s",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"192.168.0.196:4040\",image!=\"\"}) by (instance)"
    },
    {
     "expr": "sum(machine_cpu_cores{instance=~\"192.168.0.196:4040\"}) by (instance)"
    },
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{instance=~\"192.168.0.196:4040\"}[5m]) * 100)by (instance) / sum(machine_cpu_cores{instance=~\"192.168.0.196:4040\"}) by (instance)"
    },
    {
     "expr": "((sum(container_memory_usage_bytes{instance=~\"192.168.0.196:4040\"}) by (instance) - sum(container_memory_cache{instance=~\"192.168.0.196:4040\"}) by (instance)) / sum(machine_memory_bytes{instance=~\"192.168.0.196:4040\"}) by (instance)) * 100"
    },
    {
     "expr": "sum(container_memory_usage_bytes{instance=~\"192.168.0.196:4040\"}) by (instance) - sum(container_memory_cache{instance=~\"192.168.0.196:4040\"}) by (instance)"
    },
    {
     "expr": "sum(machine_memory_bytes{instance=~\"192.168.0.196:4040\"}) by (instance)"
    },
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{instance=~\"192.168.0.196:4040\"}[5m]))by (instance)"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{instance=~\"192.168.0.196:4040\"}[5m]))by (instance)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{instance=~\"192.168.0.196:4040\"}[5m]))by (instance)"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{instance=~\"192.168.0.196:4040\"}[5m]))by (instance)"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^.*\"})"
    }
   ]
  },
  {
   "title": "Filesystem Usage by Container",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^.*\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^.*\"})"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 2, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[1m])) / count(node_cpu_seconds_total{mode=\"user\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem Usage by Container",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 157 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[1m])) by (name) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"}) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 170 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[1m])) by (name) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"}) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}