{
 "title": "Fail2Ban by ttronas",
 "description": "Fail2Ban log analyses based on Loki and Promtail.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "label_name",
    "label": "Label Name",
    "query": {}
   },
   {
    "name": "label_value",
    "label": "Label Value",
    "query": {}
   },
   {
    "name": "job",
    "label": "Job",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Bans & Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors per 15m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (nodename, component) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", priority=\"ERROR\"} [$__interval]))",
     "legendFormat": "{{ nodename }}: {{component}}"
    }
   ]
  },
  {
   "title": "Bans per 15m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (nodename) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\",component=\"actions\"} |~ \"Ban .*\" [$__interval]))",
     "legendFormat": "{{ nodename }}"
    }
   ]
  },
  {
   "title": "Unbans per 15m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (nodename) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", component=\"actions\"} |~ \"Unban .*\" [$__interval]))",
     "legendFormat": "{{ nodename }}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", priority=\"ERROR\"}",
     "maxLines": 100
    }
   ]
  },
  { "title": "Complete Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Raw Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  }
 ]
}