{
 "title": "Fail2ban by TheCfU",
 "description": "Dashboard to have a Overview of the Fail2Ban logs collected via Promtail/Loki",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "lokiInstance", "label": "Loki", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Ban Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "{job=\"$job\"} |= `Ban`"
    }
   ]
  },
  {
   "title": "Geomap",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"$job\"} |= ``"
    }
   ]
  },
  { "title": "Ban Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Ban / 15m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate({job=\"$job\"} |= `Ban` [15m]))"
    }
   ]
  },
  {
   "title": "Unban / 15m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate({job=\"$job\"} |= `Unban` [15m]))"
    }
   ]
  },
  { "title": "Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Error",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{job=\"$job\"} | priority = `ERROR`"
    }
   ]
  },
  {
   "title": "Fail2Ban Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "{job=\"$job\"} |= ``"
    }
   ]
  }
 ]
}