{
 "title": "Loki2.0 Global Metrics",
 "description": "Loki metrics via 2.0",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"left dashboard-header\">\n   <img src=\"https://marketplace-assets.digitalocean.com/logos/loki-logo.svg\" style=\"height:29px;\"/>\n  <span>Loki Global Metrics</span>\n</div>"
   }
  },
  {
   "title": "Loki Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_build_info" }
   ]
  },
  {
   "title": "Message Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(loki_log_messages_total)" }
   ]
  },
  {
   "title": "Current Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "grafana_alerting_remote_alertmanager_configuration_syncs_total"
    }
   ]
  },
  {
   "title": "Alerts Event Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "grafana_alerting_alertmanager_alerts"
    }
   ]
  },
  {
   "title": "Store Series Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(loki_log_messages_total)" }
   ]
  },
  {
   "title": "Store Chunks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_chunk_stored_bytes_total)"
    }
   ]
  },
  {
   "title": "Rules Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(loki_ruler_managers_total)" }
   ]
  },
  {
   "title": "Panic ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_panic_total" }
   ]
  },
  {
   "title": "Messages Input",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(level) (rate(loki_log_messages_total[10m]))",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(loki_write_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "write_request"
    },
    {
     "expr": "# 95th percentile KV Request Duration\nhistogram_quantile(\n  0.95,\n  sum(rate(loki_kv_request_duration_seconds_bucket[$__rate_interval])) by (le)\n)",
     "legendFormat": "kv_request"
    },
    {
     "expr": "# 95th percentile Index Request Duration\nhistogram_quantile(\n  0.95,\n  sum(rate(loki_index_request_duration_seconds_bucket[$__rate_interval])) by (le)\n)",
     "legendFormat": "index_request"
    },
    {
     "expr": "# 95th percentile Ingester Client Request Duration\nhistogram_quantile(\n  0.95,\n  sum(rate(loki_ingester_client_request_duration_seconds_bucket[$__rate_interval])) by (le)\n)",
     "legendFormat": "ingester_request"
    }
   ]
  },
  {
   "title": "API Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket[$__rate_interval])) by (le,route))",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "LogQL Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket[$__rate_interval])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "LogQL  Processed bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  { "title": "Ruler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Rules Status ",
   "type": "piechart",
   "description": "not shure about evaluations",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cortex_ruler_clients", "legendFormat": "Evaluations" },
    { "expr": "grafana_emails_sent_total", "legendFormat": "Notifications" }
   ]
  },
  {
   "title": "Notifications Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(grafana_alerting_notification_latency_seconds_sum[$__rate_interval]))  by (quantile)",
     "legendFormat": "TP {{quantile}}"
    }
   ]
  },
  {
   "title": "Rule Evaluations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(grafana_alerting_schedule_query_alert_rules_duration_seconds_sum[$__rate_interval]))\n  by (quantile)",
     "legendFormat": "rules_duration_seconds_sum"
    },
    {
     "expr": "sum(rate(grafana_alerting_schedule_query_alert_rules_duration_seconds_bucket[$__rate_interval]))\n  by (quantile)",
     "legendFormat": "grafana_duration_seconds_bucket"
    },
    {
     "expr": "sum(rate(cortex_ruler_sync_rules_duration_seconds_bucket[$__rate_interval]))\n  by (quantile)",
     "legendFormat": "cortex_duration_seconds_bucket"
    }
   ]
  },
  { "title": "Cache ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Cache Request  Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(cortex_bucket_store_cached_postings_fetch_duration_seconds_bucket[$__rate_interval])) \n  by (le)\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Cache Value Size bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(cortex_querier_request_message_bytes_bucket[$__rate_interval])) by (le)\n)\n",
     "legendFormat": "{{name}} / {{method}}"
    }
   ]
  },
  {
   "title": "Hits Keys",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  rate(cortex_frontend_query_result_cache_hits_total[$__rate_interval]))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(\n  rate(cortex_bucket_store_series_hash_cache_hits_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Background Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cortex_query_frontend_queue_length",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fetched Keys",
   "type": "timeseries",
   "description": "kp",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cortex_frontend_query_result_cache_requests_total",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Index Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_bucket_index_load_duration_seconds_bucket[$__rate_interval])) by (le,operation))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_bucket_store_indexheader_lazy_load_duration_seconds_bucket[$__rate_interval])) by (le,operation))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chunk Store Chunks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_chunk_store_chunks_per_query_bucket[5m])) by (le))",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "Table-Manager Sync Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_table_manager_sync_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  { "title": "Distributor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Received Lines / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (tenant) (rate(loki_distributor_lines_received_total[5m]))",
     "legendFormat": "distributor / {{ tenant}}"
    }
   ]
  },
  {
   "title": "Distributor  Received bytes / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[5m])) by (tenant)",
     "legendFormat": "distributor / {{tenant}}"
    }
   ]
  },
  {
   "title": "batch appends sent to ingesters / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki_distributor_ingester_appends_total[5m])",
     "legendFormat": "successed"
    },
    {
     "expr": "loki_distributor_ingester_append_failures_total",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Store Series / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(loki_store_series_total{ }[$__rate_interval]))",
     "legendFormat": "sa"
    }
   ]
  },
  { "title": "Ingster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Blocks / Chunk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_blocks_per_chunk_bucket[5m])) by (le))",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Chunk Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket[5m])) by (le))",
     "legendFormat": "chunk size"
    }
   ]
  },
  {
   "title": "Chunk Age",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_age_seconds_bucket[5m])) by (le))",
     "legendFormat": "ages"
    }
   ]
  },
  {
   "title": "Chunk Compression Ratios",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket[5m])) by (le))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Chunk Encode Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_encode_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "durations."
    }
   ]
  },
  {
   "title": "Lines / Chunk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_entries_bucket[5m])) by (le))",
     "legendFormat": "lines"
    }
   ]
  },
  {
   "title": "Chunk Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki_ingester_chunks_created_total[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "sum by (reason) (rate(loki_ingester_chunks_flushed_total[5m]))",
     "legendFormat": "flush / {{ reason }}"
    },
    {
     "expr": "sum by (fake) (rate(loki_ingester_chunks_stored_total[5m]))",
     "legendFormat": "stored"
    },
    {}
   ]
  },
  {
   "title": "Chunks in Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "loki_ingester_memory_chunks", "legendFormat": "chunks" }
   ]
  },
  {
   "title": "Chunks in Streams",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (tenan) (loki_ingester_memory_streams)",
     "legendFormat": "streams"
    }
   ]
  },
  {
   "title": "Strams Stats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki_ingester_streams_created_total[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "rate(loki_ingester_streams_removed_total[5m])",
     "legendFormat": "delete"
    }
   ]
  }
 ]
}