{
 "title": "PHP-FPM 2 mine",
 "description": "PHP-FPM detailed page for single FPM pool.",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "label_values(php_fpm_accepted_connections_total, instance)"
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "Interval", "label": "Time Interval", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "Socket",
    "label": "Socket",
    "query": "label_values(php_fpm_accepted_connections_total, socket_path)"
   }
  ]
 },
 "panels": [
  { "title": "PHP FPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PHP-FPM Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "phpfpm_up" }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "time()-(phpfpm_start_since) ", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "Workers  Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "phpfpm_start_since / phpfpm_max_active_processes"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Accepted Connections Rate",
   "type": "timeseries",
   "description": "Total number of accepted connections",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(phpfpm_accepted_connections[$Interval])",
     "legendFormat": "Accepted Connections Rate"
    }
   ]
  },
  {
   "title": "Processes TODO",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "phpfpm_max_active_processes", "legendFormat": "Max Active" },
    { "expr": "phpfpm_active_processes", "legendFormat": "Active" },
    { "expr": "phpfpm_idle_processes", "legendFormat": "Idle" },
    { "expr": "phpfpm_max_children_reached", "legendFormat": "Max Children" }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Slow Requests Rate",
   "type": "timeseries",
   "description": "Number of requests that exceed request_slowlog_timeout",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(phpfpm_slow_requests[$Interval])",
     "legendFormat": "Slow Requests Rate "
    }
   ]
  },
  {
   "title": "Listen Queue Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "phpfpm_listen_queue", "legendFormat": "Queue" },
    { "expr": "phpfpm_listen_queue_length", "legendFormat": "Queue Length" }
   ]
  }
 ]
}