services:
  alloy:
    image: grafana/alloy:v1.5.1
    pull_policy: always
    container_name: alloy
    restart: on-failure
    environment:
      REMOTE_WRITE_HOST: mimir:9009
      LOKI_HOST: loki:3100
      TEMPO_HOST: tempo:4317
      PYROSCOPE_HOST: pyroscope:4040
    depends_on:
      - mimir
      - loki
      - tempo
      - pyroscope
      - modsecurity-waf
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=experimental 
    ports:
      - "12345:12345"
      - "5317:4317"         # OTLP gRPC
      - "4318:4318"         # OTLP HTTP/protobuf
    volumes:
      - ./config/alloy:/etc/alloy
      - ../../.data/apache:/var/log/apache2
      - modsec-logs:/var/log/modsec
      - fail2ban-logs:/var/log/fail2ban
      - geoip:/geoip
    develop:
      watch:
        - path: ./config/alloy
          action: restart











#dockerdocker run -v /home/user-debian/alloy_test/alloy/example/web/hello:/var/www/html/public  -v /home/user-debian/alloy_test/alloy/example/config/web/apache/status/php-fpm.conf:/etc/apache2/conf-available/status/php-fpm.conf  -v /home/user-debian/alloy_test/alloy/example/config/web/apache/http.conf:/etc/apache2/vhost-templates/http.conf -p 8080:8080  --name web -d   serversideup/php:8.4-fpm-apache
#services:

  # otel_collector:
  #   container_name: otel_collector
  #   image: otel/opentelemetry-collector-contrib:0.76.1
  #   pull_policy: always
  #   restart: on-failure
  #   volumes:
  #     - ./config/otelcollector.yaml:/etc/otelcol-config.yml
  #   # command:
  #     # - run
  #     # - /etc/alloy/config.alloy
  #     # - --server.http.listen-addr=0.0.0.0:12345
  #   ports:
  #     - "5317:4317"     # OTLP gRPC
  #     - "5318:4318"     # OTLP HTTP
  #     - "12346:12345"
