services:
  apache:
    image: serversideup/php:8.4-fpm-apache #https://serversideup.net/open-source/docker-php/docs/getting-started/these-images-vs-others
    restart: on-failure
    container_name: apache
    volumes:
      - ./web/hello/:/var/www/html/public
      - ./config/apache/http.conf:/etc/apache2/vhost-templates/http.conf
      - ../../.data/apache:/var/log/apache2
    ports:
      - "8080:8080"
      - "9000:9000" # move to seperate network 
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthcheck" ]
      interval: 1s
      start_period: 10s
      timeout: 10s
      retries: 5
    # env_file:
    environment:
      - LOG_OUTPUT_LEVEL=info
      # - APACHE_STATUS_URL=http://localhost:8080/server-status?auto  
    #dockerdocker run -v /
  ################  FPM  ###############################  FPM  #########################  
  # fpm:
  #   image: serversideup/php:8.4-fpm-alpine
  #   container_name: fpm
  #   volumes:
  #     - ./web/hello/:/var/www/html
  #     - ../../.data/php-fpm:/var/log/php-fpm
  #   ports:
  #     - "9000:9000"
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://localhost:9000/status" ]
  #     interval: 1s
  #     start_period: 10s
  #     timeout: 10s
  #     retries: 5

  






  # TODO
#   Umask for running applications

# For all of our images we provide the ability to override the default umask settings for services started within the containers using the optional -e UMASK=022 setting. Keep in mind umask is not chmod it subtracts from permissions based on it's value it does not add. Please read up here⁠

# before asking for support.
# User / Group Identifiers

# When using volumes (-v flags), permissions issues can arise between the host OS and the container, we avoid this issue by allowing you to specify the user PUID and group PGID.

# Ensure any volume directories on the host are owned by the same user you specify and any permissions issues will vanish like magic.

# In this instance PUID=1000 and PGID=1000, to find yours use id your_user as below:

# id your_user

# Example output:

# uid=1000(your_user) gid=1000(your_user) groups=1000(your_user)

