services:
  mimir:
    image: grafana/mimir:2.14.3
    restart: on-failure
    container_name: mimir
    command:
      - -config.file=/etc/mimir-config/mimir.yaml
    volumes:
      - ./config/mimir:/etc/mimir-config
    ports:
      - "9009:9009"

  loki:
    image: grafana/loki:3.4.1
    container_name: loki
    restart: on-failure
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:2.7.0
    container_name: tempo
    restart: on-failure
    command:
      - "-config.file=/etc/tempo-config/tempo.yaml"
      - "-storage.trace.backend=local"                  # tell tempo where to permanently put traces
      - "-storage.trace.local.path=/tmp/tempo/traces"
      - "-storage.trace.wal.path=/tmp/tempo/wal"        # tell tempo where to store the wal
      - "-auth.enabled=false"                           # disables the requirement for the X-Scope-OrgID header
      - "-server.http-listen-port=3200"
    volumes:
      - ./config/tempo:/etc/tempo-config
    ports:
      - "3200:3200"
      - "4317:4317"

  pyroscope:
    image: grafana/pyroscope:1.5.0
    container_name: pyroscope
    restart: on-failure
    ports:
      - "4040:4040"

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: on-failure
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=mydb
      - MARIADB_USER=user
      - MARIADB_PASSWORD=user
    volumes:
      - .data_local/mariadb_data:/var/lib/mysql
      - ./config/mariadb/init_metric_user.sql:/docker-entrypoint-initdb.d/init_metrics.sql:ro
    ports:
      - "3306:3306"