services:
  mimir:
    image: grafana/mimir:2.17.0
    restart: on-failure
    container_name: mimir
    command:
      - -config.file=/etc/mimir-config/mimir.yaml
    volumes:
      - ./config/mimir:/etc/mimir-config
    ports:
      - "9009:9009"
    networks:
      - website-network

  loki:
    image: grafana/loki:3.5.3
    container_name: loki
    restart: on-failure
    ports:
      - "3100:3100"
    networks:
      - website-network
    volumes:
      - ./config/loki/loki-config.yaml:/etc/loki/local-config.yaml
    #command: -config.file=/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:2.8.2
    container_name: tempo
    restart: on-failure
    command:
      - "-config.file=/etc/tempo-config/tempo.yaml"
      - "-storage.trace.backend=local"                  # tell tempo where to permanently put traces
      - "-storage.trace.local.path=/tmp/tempo/traces"
      - "-storage.trace.wal.path=/tmp/tempo/wal"        # tell tempo where to store the wal
      - "-auth.enabled=false"                           # disables the requirement for the X-Scope-OrgID header
      - "-server.http-listen-port=3200"
    volumes:
      - ./config/tempo:/etc/tempo-config
    ports:
      - "3200:3200"
      - "4317:4317"
    networks:
      - website-network

  pyroscope:
    image: grafana/pyroscope:1.14.0
    container_name: pyroscope
    restart: on-failure
    ports:
      - "4040:4040"
    networks:
      - website-network

  global-db:
    pull_policy: always
    image: observabilitystack/geoip-api:latest
    container_name: global-db
    restart: no
    networks:
      - website-network
    command: >
      sh -c "cp -f /srv/GeoLite2-City.mmdb /share/ && exit 0"
    volumes:
      - geoip:/share