services:
#https://github.com/hipages/php-fpm_exporter
  phpfpmexporter:
    image: hipages/php-fpm_exporter
    container_name: phpfpmexporter
    environment:
      - PHP_FPM_SCRAPE_URI=tcp://apache:9000/status
      # - PHP_FPM_LOG_LEVEL= "info"
      - PHP_FPM_LOG_LEVEL=debug
    ports:
      - "9253:9253"
      # - "9250:9250"
    depends_on:
      - apache

  apacheexporter:
    image: bitnami/apache-exporter:latest
    container_name: apacheexporter
    # environment:
      # - APACHE_STATUS_URL=http://apache:8080/server-status?auto
      # - SCRAPE_URI=http://apache:8080/server-status?auto
    ports:
      - "9117:9117"
    command:
      - --scrape_uri=http://apache:8080/server-status?auto
    depends_on:
      - apache

  mysqldexporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqldexporter
    restart: unless-stopped
    ports:
      - "9104:9104"
    volumes:
      - ./config/mysql_exporter/.my.cnf:/.my.cnf
    environment:
      - MYSQLD_EXPORTER_PASSWORD=XXXXXXXX
    depends_on:
      - mariadb

  alloy:
    image: grafana/alloy:v1.5.1
    pull_policy: always
    container_name: alloy
    restart: on-failure
    environment:
      REMOTE_WRITE_HOST: mimir:9009
      LOKI_HOST: loki:3100
      TEMPO_HOST: tempo:4317
      PYROSCOPE_HOST: pyroscope:4040
    depends_on:
      - mimir
      - loki
      - tempo
      - pyroscope
      - modsecurity-waf
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=experimental # Enable all functionality
    ports:
      - "12345:12345"
      - "5317:4317"         # OTLP gRPC
      - "4318:4318"         # OTLP HTTP/protobuf
    volumes:
      - ./config/alloy:/etc/alloy
      - modsec-logs:/var/log/modsec # mount logs for alloy to push to db´s















#dockerdocker run -v /home/user-debian/alloy_test/alloy/example/web/hello:/var/www/html/public  -v /home/user-debian/alloy_test/alloy/example/config/web/apache/status.conf:/etc/apache2/conf-available/status.conf  -v /home/user-debian/alloy_test/alloy/example/config/web/apache/http.conf:/etc/apache2/vhost-templates/http.conf -p 8080:8080  --name web -d   serversideup/php:8.4-fpm-apache
#services:

  # otel_collector:
  #   container_name: otel_collector
  #   image: otel/opentelemetry-collector-contrib:0.76.1
  #   pull_policy: always
  #   restart: on-failure
  #   volumes:
  #     - ./config/otelcollector.yaml:/etc/otelcol-config.yml
  #   # command:
  #     # - run
  #     # - /etc/alloy/config.alloy
  #     # - --server.http.listen-addr=0.0.0.0:12345
  #   ports:
  #     - "5317:4317"     # OTLP gRPC
  #     - "5318:4318"     # OTLP HTTP
  #     - "12346:12345"
