services:
#https://github.com/hipages/php-fpm_exporter
  phpfpmexporter:
    build:
      context: ../images/exporter-php
      dockerfile: Dockerfile
    image: localhost/php-fpm_exporter:latest
    container_name: phpfpmexporter
    healthcheck:
        test: ["CMD-SHELL", "wget -q --spider http://localhost:9253/metrics || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 3
    environment:
      - PHP_FPM_SCRAPE_URI="http://apache:80/status/php-fpm"
      - PHP_FPM_LOG_LEVEL=debug
      - PHP_FPM_FIX_PROCESS_COUNT=true
    ports:
      - "9253:9253"
    depends_on:
      - apache

  apacheexporter:
    image: bitnami/apache-exporter:latest
    container_name: apacheexporter
    # environment:
      # - APACHE_STATUS_URL=http://apache:80/server-status?auto
      # - SCRAPE_URI=http://apache:80/server-status?auto
    ports:
      - "9117:9117"
    command:
      - --scrape_uri=http://apache:80/server-status?auto
    depends_on:
      - apache

  mysqldexporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqldexporter
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:9104/metrics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "9104:9104"
    volumes:
      - ./config/mysql_exporter/.my.cnf:/.my.cnf
    environment:
      - MYSQLD_EXPORTER_PASSWORD=XXXXXXXX
    depends_on:
      - mariadb
  # cadvisor:
  #   image:privileged:latest
  #   ports:
  #     - 1080:8080
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro

  docker_state_exporter:
    image: karugaru/docker_state_exporter
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/metrics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    container_name: docker_state_exporter
    volumes:
      - type: bind
        source: /run/user/1001/podman/podman.sock
        target: /var/run/docker.sock
    ports:
      - 8085:8080

