services:
#https://github.com/hipages/php-fpm_exporter
  phpfpmexporter:
    build:
      context: ../images/exporter-php
      dockerfile: Dockerfile
    image: own/php-fpm_exporter:latest
    container_name: phpfpmexporter
    environment:
      - PHP_FPM_SCRAPE_URI="http://apache:80/status/php-fpm"
      - PHP_FPM_LOG_LEVEL=debug
      - PHP_FPM_FIX_PROCESS_COUNT=true
    ports:
      - "9253:9253"
    depends_on:
      - apache

  apacheexporter:
    image: bitnami/apache-exporter:latest
    container_name: apacheexporter
    # environment:
      # - APACHE_STATUS_URL=http://apache:80/server-status?auto
      # - SCRAPE_URI=http://apache:80/server-status?auto
    ports:
      - "9117:9117"
    command:
      - --scrape_uri=http://apache:80/server-status?auto
    depends_on:
      - apache

  mysqldexporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqldexporter
    restart: unless-stopped
    ports:
      - "9104:9104"
    volumes:
      - ./config/mysql_exporter/.my.cnf:/.my.cnf
    environment:
      - MYSQLD_EXPORTER_PASSWORD=XXXXXXXX
    depends_on:
      - mariadb


