{
 "title": "ModSecurity Log JSON WAF OWASP CRS for Apache/NGINX",
 "description": "Loki Promtail",
 "tags": [ "loki" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "ModSecurity Requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (request_request_line)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} | json [$__interval])))"
    }
   ]
  },
  {
   "title": "ModSecurity IP's",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (transaction_remote_address)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} | json [$__interval])))"
    }
   ]
  },
  {
   "title": "ModSecurity Rules",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (audit_data_action_message)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} | json [$__interval])))"
    }
   ]
  },
  {
   "title": "ModSecurity  Browsers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (request_headers_User_Agent)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} | json [$__interval])))"
    }
   ]
  },
  {
   "title": "ModSecurity hosts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (request_headers_Host)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} | json [$__interval])))"
    }
   ]
  },
  {
   "title": "ModSecurity by HTTP response status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (response_status)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} | json [$__interval])))"
    }
   ]
  },
  {
   "title": "GeoMap Locations",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (request_headers_Cf_Ipcountry)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} | json [$__interval]))"
    }
   ]
  },
  {
   "title": "ModSecurity Rate Conf Types",
   "type": "timeseries",
   "description": "Rules Conf",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (request_headers_Host)(rate(({filename=\"/var/log/modsec/modsec_audit.log\"} |~ `932\\d{3}`)[5m]))"
    },
    {
     "expr": "sum by (request_headers_Host)(rate(({filename=\"/var/log/modsec/modsec_audit.log\"} |~ `942\\d{3}`)[5m]))"
    },
    {
     "expr": "sum by (request_headers_Host)(rate(({filename=\"/var/log/modsec/modsec_audit.log\"} |~ `920\\d{3}`)[5m]))"
    },
    {
     "expr": "sum by (request_headers_Host)(rate(({filename=\"/var/log/modsec/modsec_audit.log\"} |~ `913\\d{3}`)[5m]))"
    },
    {
     "expr": "sum by (request_headers_Host)(rate(({filename=\"/var/log/modsec/modsec_audit.log\"} |~ `949\\d{3}`)[5m]))"
    },
    {
     "expr": "sum by (request_headers_Host)(rate(({filename=\"/var/log/modsec/modsec_audit.log\"} |~ `980\\d{3}`)[5m]))"
    },
    {
     "expr": "sum by (request_headers_Host)(rate(({filename=\"/var/log/modsec/modsec_audit.log\"} |~ `930\\d{3}`)[5m]))"
    },
    {
     "expr": "sum by (request_headers_Host)(rate(({filename=\"/var/log/modsec/modsec_audit.log\"} |~ `941\\d{3}`)[5m]))"
    }
   ]
  },
  {
   "title": "ModSecurity Countries",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (request_headers_Cf_Ipcountry)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} | json [$__interval])))"
    }
   ]
  },
  {
   "title": "ModSecurity  Log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/modsec/modsec_audit.log\"} \r\n| json\r\n| line_format \"Client {{.transaction_remote_address}} from {{.request_headers_Cf_Ipcountry}} with request {{.request_request_line}} status {{.response_status}} at {{.request_headers_Host}}\""
    }
   ]
  }
 ]
}