{
 "title": "Apache HTTP server logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Metrics datasource", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki datasource", "query": "loki" },
   { "name": "job", "label": "job", "query": "label_values(apache_up, job)" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(apache_up,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Error logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs by level",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=~\"$job\", logtype=\"error\", level!=\"\"}[$__interval])) by (level)",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Apache error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"$job\", instance=~\"$instance\", logtype=\"error\"}"
    }
   ]
  },
  { "title": "Access logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Logs by HTTP codes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (le,job) (increase(apache_response_http_codes_bucket{le!=\"+Inf\", job=~\"$job\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Apache access logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{job=~\"$job\", instance=~\"$instance\", logtype=\"access\"}"
    }
   ]
  }
 ]
}