{
 "title": "Apache2",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(apache_up, namespace)"
   },
   {
    "name": "state",
    "label": "Scoreboard State",
    "query": "label_values(apache_scoreboard, state)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(apache_uptime_seconds_total{namespace=~\"^$namespace\"}) by (namespace,pod)",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Apache Up / Down",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(apache_up{namespace=~\"^$namespace\"} == 1) by (pod)",
     "legendFormat": "Up - {{pod}}"
    }
   ]
  },
  {
   "title": "Current total kbytes sent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "rate(apache_sent_kilobytes_total{namespace=~\"^$namespace\"}[5m])",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Current total apache accesses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(apache_accesses_total{namespace=~\"^$namespace\"}[5m])",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Apache scoreboard statuses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apache_scoreboard{namespace=~\"^$namespace\",state=~\"^$state\"}",
     "legendFormat": "{{namespace}} - {{pod}} - {{ state }}"
    }
   ]
  },
  {
   "title": "Apache worker statuses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apache_workers{namespace=~\"^$namespace\",state=~\"busy\"}\n",
     "legendFormat": "{{namespace}} - {{pod}} - {{ state }}"
    },
    {
     "expr": "apache_workers{namespace=~\"^$namespace\",state=~\"idle\"}",
     "legendFormat": "{{namespace}} - {{pod}} - {{ state }}"
    }
   ]
  },
  {
   "title": "Apache CPU load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apache_cpuload{namespace=~\"^$namespace\"}",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  }
 ]
}