{
 "title": "ModSecurity Apache WAF OWASP CRS 2",
 "description": "Loki Promtail (not using JON ModSecurity audit log)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ModSecurity Rules",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (msg)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} \r\n|= \"Message: Warning.\"\r\n| pattern `<_> [file \"<file>\"] [line \"<line>\"] [id \"<id>\"] [msg \"<msg>\"] <_> [severity \"<severity>\"] [ver \"<ver>\"] [tag \"<tag>\"]`\r\n[$__interval])))"
    },
    {
     "direction": "backward",
     "expr": "topk(10, sum by (msg)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} \r\n| pattern `<_> [file \"<file>\"] [line <line>] [level <level>] [client <client>] <_> [file \"<file2>\"] [line \"<line1>\"] [id \"<id>\"] [msg \"<msg>\"] <_> [ver \"<ver>\"] <tag> [hostname \"<hostname>\"] [uri \"<uri>\"] [unique_id \"<unique_id>\"]`\r\n[$__interval])))"
    }
   ]
  },
  {
   "title": "ModSecurity URI",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (uri)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} \r\n|= \"Apache-Error\"\r\n| pattern `<_> [file \"<file>\"] [line <line>] [level <level>] [client <client>] <_> [file \"<file2>\"] [line \"<line1>\"] [id \"<id>\"] [msg \"<msg>\"] <_> [ver \"<ver>\"] <tag> [hostname \"<hostname>\"] [uri \"<uri>\"] [unique_id \"<unique_id>\"]`\r\n[$__interval])))"
    }
   ]
  },
  {
   "title": "ModSecurity Type Rules",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (file)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"}\r\n | pattern `<_> [file \"<file>\"] [line <line>] [level <level>] [client <client>] <_> [file \"<file2>\"] [line \"<line1>\"] [id \"<id>\"] [msg \"<msg>\"] <_> [ver \"<ver>\"] <tag> [hostname \"<hostname>\"] [uri \"<uri>\"] [unique_id \"<unique_id>\"]`\r\n [$__interval])))"
    }
   ]
  },
  {
   "title": "ModSecurity Requests",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (get)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} \r\n|= \"GET\"\r\n| pattern `GET <get>`\r\n [$__interval])))"
    }
   ]
  },
  {
   "title": "ModSecurity attackers browsers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (user_agent)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} \r\n|= \"User-Agent:\"\r\n| pattern `User-Agent: <user_agent>`\r\n [$__interval])))"
    }
   ]
  },
  {
   "title": "ModSecurity Countries",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (Ipcountry)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} \r\n|= \"Cf-Ipcountry:\"\r\n| pattern `Cf-Ipcountry: <Ipcountry>`\r\n [$__interval])))"
    }
   ]
  },
  {
   "title": "ModSecurity IP's",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (ip)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} \r\n|= \"X-Forwarded-For:\"\r\n| pattern `X-Forwarded-For: <ip>`\r\n [$__interval])))\r\n"
    }
   ]
  },
  {
   "title": "ModSecurity Rate Conf Types",
   "type": "timeseries",
   "description": "Rules Conf",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by (request_headers_Host)(rate(({filename=\"/var/log/modsec/modsec_audit.log\"} |~ `932\\d{3}`)[5m]))"
    },
    {
     "expr": "sum by (request_headers_Host)(rate(({filename=\"/var/log/modsec/modsec_audit.log\"} |~ `942\\d{3}`)[5m]))"
    },
    {
     "expr": "sum by (request_headers_Host)(rate(({filename=\"/var/log/modsec/modsec_audit.log\"} |~ `920\\d{3}`)[5m]))"
    },
    {
     "expr": "sum by (request_headers_Host)(rate(({filename=\"/var/log/modsec/modsec_audit.log\"} |~ `913\\d{3}`)[5m]))"
    },
    {
     "expr": "sum by (request_headers_Host)(rate(({filename=\"/var/log/modsec/modsec_audit.log\"} |~ `949\\d{3}`)[5m]))"
    },
    {
     "expr": "sum by (request_headers_Host)(rate(({filename=\"/var/log/modsec/modsec_audit.log\"} |~ `980\\d{3}`)[5m]))"
    },
    {
     "expr": "sum by (request_headers_Host)(rate(({filename=\"/var/log/modsec/modsec_audit.log\"} |~ `930\\d{3}`)[5m]))"
    },
    {
     "expr": "sum by (request_headers_Host)(rate(({filename=\"/var/log/modsec/modsec_audit.log\"} |~ `941\\d{3}`)[5m]))"
    }
   ]
  },
  {
   "title": "GeoMap Locations",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (Ipcountry)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"}\r\n|= \"Cf-Ipcountry:\"\r\n| pattern `Cf-Ipcountry: <Ipcountry>`\r\n [$__interval]))"
    }
   ]
  },
  {
   "title": "ModSecurity Engine Mode",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (engine_mode)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} \r\n|= \"Engine-Mode:\"\r\n| pattern `Engine-Mode: \"<engine_mode>\"`\r\n [$__interval])))"
    }
   ]
  },
  {
   "title": "ModSecurity hosts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (hostname)\r\n(count_over_time({filename=\"/var/log/modsec/modsec_audit.log\"} \r\n| pattern `<_> [file \"<file>\"] [line <line>] [level <level>] [client <client>] <_> [file \"<file2>\"] [line \"<line1>\"] [id \"<id>\"] [msg \"<msg>\"] <_> [ver \"<ver>\"] <tag> [hostname \"<hostname>\"] [uri \"<uri>\"] [unique_id \"<unique_id>\"]`\r\n[$__interval])))"
    }
   ]
  },
  {
   "title": "ModSecurity  Log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/modsec/modsec_audit.log\"} |= \"Apache-Error\"\r\n| pattern `<_> [file \"<file>\"] [line <line>] [level <level>] [client <client>] <_> [file \"<file2>\"] [line \"<line1>\"] [id \"<id>\"] [msg \"<msg>\"] <_> [ver \"<ver>\"] <tag> [hostname \"<hostname>\"] [uri \"<uri>\"] [unique_id \"<unique_id>\"]`\r\n| line_format \"Client {{.client}} with request {{.uri}} at {{.hostname}}\""
    }
   ]
  }
 ]
}